[Rollout] Production Rollout Dec 16, 2020
dotnet/arcade-services pull request #1494
Opened 2020-12-15 18:19 UTC by sunandabalu

2020-12-15 19:21 UTC, MattGal requested changes

2020-12-15 19:21 UTC, MattGal commented on eng/deploy.yaml
> + - job: deployStatus
as @riarenas notes this change deleted one char of whitespace text and needs to be re-indented

2020-12-16 15:59 UTC, riarenas approved these changes

2020-12-16 16:01 UTC, MattGal approved these changes

2020-12-16 18:53 UTC, merged