Ignore release notes on rollout issues
dotnet/arcade-services pull request #2100
Opened 2022-11-08 19:02 UTC by jonfortescue

https://github.com/dotnet/arcade/issues/11433

2022-11-08 19:06 UTC, MattGal approved these changes

2022-11-08 19:09 UTC, michellemcdaniel requested changes
Same feedback as on the machines PR

2022-11-09 18:35 UTC, riarenas approved these changes

2022-11-09 18:44 UTC, MattGal approved these changes

2022-11-09 19:27 UTC, michellemcdaniel approved these changes

2022-11-09 19:45 UTC, merged