Lower the severity of missing next-rotatuion-on tag log record.
dotnet/arcade-services pull request #2234
Opened 2023-03-02 12:30 UTC by andriipatsula

https://github.com/dotnet/arcade/issues/12712

2023-03-02 12:35 UTC, oleksandr-didyk approved these changes

2023-03-02 12:52 UTC, tkapin requested changes
Before reducing the error to warning, could you please check with Redmond folks what is our policy to have the next rotation tags set?

2023-03-02 13:42 UTC, premun approved these changes
As discussed offline, there's most likely no policy. This functionality was just introduced on Friday and would block all of our repos most likely so we should first figure out how to roll it out (e.g. tag secrets first?).

2023-03-02 16:08 UTC, premun commented
Apparently, there's over 100 of them. We thought we need to rush this in for the rollout but then we noticed we're not rolling out today, so I guess we can now fix those instead, yeah.

2023-03-02 16:09 UTC, riarenas commented
Where are the 100 secrets blocking the build? it looks like it's 9 of them looking at the latest builds?

2023-03-02 17:16 UTC, MattGal commented
This error specifically needs to exist because we have had secrets fail to get cycled and affect production systems multiple times for the reason the error is trying to block. Downgrading it to a warning is downgrading it to being ignored like all the other warnings.

If you don't want to just run secret-manager synchronize in a loop, you could just update the tags manually once setting reasonable dates in the tags.  I truly think demoting this to not breaking the weekly build is not a good idea.

2023-03-02 17:51 UTC, closed without merging

2023-03-02 17:52 UTC, tkapin commented
I agree with @riarenas and @MattGal. Expiring secrets are common source of problems and we shouldn't lower our bar here. We should fix the secrets instead.

2023-03-03 07:36 UTC, premun commented
I definitely think we should have this error but I also think we should first tag all the secrets before this starts failing builds everywhere?

2023-03-03 07:36 UTC, premun commented
> Where are the 100 secrets blocking the build?

@andriipatsula mentioned that here: https://github.com/dotnet/arcade/issues/12712#issuecomment-1451843273

2023-03-03 14:45 UTC, riarenas commented
That was an incorrect interpretation of the warnings. There are only 9 secrets to fix in arcade-services.

2023-03-03 15:06 UTC, premun commented
I'll tag those.

I guess Andrii's information comes from local run of the tool which for some reason returns way more than that (this is just one manifest):
```
Synchronizing secrets contained in D:\github\arcade-services\.vault-config\dotnet-grafana-production.yaml
error : Key Vault Secret 'deployment-staging-api-key' is missing next-rotation-on tag, using the end of time as value. Please force a rotation or manually set this value.
error : Key Vault Secret 'dnc-eng-app-insights-api-key' is missing next-rotation-on tag, using the end of time as value. Please force a rotation or manually set this value.
error : Key Vault Secret 'dotnet-eng-app-insights-api-key' is missing next-rotation-on tag, using the end of time as value. Please force a rotation or manually set this value.
error : Key Vault Secret 'dotnet-eng-grafana-staging-westus2-cloudapp-azure' is missing next-rotation-on tag, using the end of time as value. Please force a rotation or manually set this value.
error : Key Vault Secret 'dotnet-eng-grafana-westus2-cloudapp-azure' is missing next-rotation-on tag, using the end of time as value. Please force a rotation or manually set this value.
error : Key Vault Secret 'dotnet-grafana-github-oauth-app-secret' is missing next-rotation-on tag, using the end of time as value. Please force a rotation or manually set this value.
error : Key Vault Secret 'dotnet-grafana-production-github-oauth-app-secret' is missing next-rotation-on tag, using the end of time as value. Please force a rotation or manually set this value.
error : Key Vault Secret 'dotnet-grafana-staging-github-oauth-app-secret' is missing next-rotation-on tag, using the end of time as value. Please force a rotation or manually set this value.
error : Key Vault Secret 'dotneteng-status-app-insights-api-key' is missing next-rotation-on tag, using the end of time as value. Please force a rotation or manually set this value.
error : Key Vault Secret 'dotnetgrafana-storage-account-key' is missing next-rotation-on tag, using the end of time as value. Please force a rotation or manually set this value.
error : Key Vault Secret 'fr-bot-notifications-teams-notification-url' is missing next-rotation-on tag, using the end of time as value. Please force a rotation or manually set this value.
error : Key Vault Secret 'grafana-admin-api-key-hot' is missing next-rotation-on tag, using the end of time as value. Please force a rotation or manually set this value.
error : Key Vault Secret 'grafana-aes-256-secret-key' is missing next-rotation-on tag, using the end of time as value. Please force a rotation or manually set this value.
error : Key Vault Secret 'grafana-app-insights-api-key' is missing next-rotation-on tag, using the end of time as value. Please force a rotation or manually set this value.
error : Key Vault Secret 'grafana-datasource-ai-grafana-client-secret' is missing next-rotation-on tag, using the end of time as value. Please force a rotation or manually set this value.
error : Key Vault Secret 'grafana-viewer-api-key' is missing next-rotation-on tag, using the end of time as value. Please force a rotation or manually set this value.
error : Key Vault Secret 'helix-app-insights-api-key' is missing next-rotation-on tag, using the end of time as value. Please force a rotation or manually set this value.
error : Key Vault Secret 'helix-autoscale-app-insights-api-key' is missing next-rotation-on tag, using the end of time as value. Please force a rotation or manually set this value.
error : Key Vault Secret 'helix-client-app-insights-api-key' is missing next-rotation-on tag, using the end of time as value. Please force a rotation or manually set this value.
error : Key Vault Secret 'helix-grafana-ad-client-secret' is missing next-rotation-on tag, using the end of time as value. Please force a rotation or manually set this value.
error : Key Vault Secret 'helixpoolprovider-dncengpublic-prod-api-key' is missing next-rotation-on tag, using the end of time as value. Please force a rotation or manually set this value.
error : Key Vault Secret 'key-vault-app-secret' is missing next-rotation-on tag, using the end of time as value. Please force a rotation or manually set this value.
error : Key Vault Secret 'maestro-app-insights-api-key' is missing next-rotation-on tag, using the end of time as value. Please force a rotation or manually set this value.
error : Key Vault Secret 'pool-provider-internal-app-insights-api-key' is missing next-rotation-on tag, using the end of time as value. Please force a rotation or manually set this value.
error : Key Vault Secret 'pool-provider-public-app-insights-api-key' is missing next-rotation-on tag, using the end of time as value. Please force a rotation or manually set this value.
error : Key Vault Secret 'status-app-insights-api-key' is missing next-rotation-on tag, using the end of time as value. Please force a rotation or manually set this value.
```

I guess the version of SecretManager used in this repo might be older?

2023-03-03 15:06 UTC, premun commented
I'll tag those 9 and see how the build does

2023-03-03 15:23 UTC, tkapin commented
Do we know why do the local and pipeline runs give different results? If not, it'd be good to investigate.

2023-03-03 15:53 UTC, premun commented
I deleted some secrets that were expired a long time ago and were disabled in the KeyVault but there are still some left. However, there are many things I don't understand about this "next-rotation-on" tag/feature:
- Why is it checking on all secrets in the KeyVault and not just those in the manifest?
- What should the value of the tag be? Same as expiration time? If yes, why do we duplicate this since information that can get out of sync? I didn't find any information about this tag in the README.
- What Tomas said - why is the local run returning a different result?

2023-03-03 17:00 UTC, premun commented
I did some investigations and checked the code and..

1. We're getting the secrets from the manifest. Then we get all the secrets from the KeyVault so that we can print extraneous secrets. This error is thrown/logged for every secret when enumerating any KeyVault, regardless of whether the secret is or is not in the manifest. I think this is wrong and ends up flagging all secrets in the KeyVault.
2. Looking at how the build behaves, it's only printing the first error per each KeyVault. Local run prints all (so there would eventually be over 100 of them in the pipeline).

So I believe this logic should be changed to only log missing tags for secrets from the manifest.

2023-03-03 17:10 UTC, premun commented
We could move the logging statement out but I have no knowledge about whether this should apply to all secrets or just the KeyVault ones..

Something like this:
![image](https://user-images.githubusercontent.com/7013027/222783693-d18f4db0-cb8e-4d61-8b68-95a051bed236.png)

(now it logs from the first line when it gets all secrets)

2023-03-03 17:18 UTC, tkapin commented
Thanks for investigating this. Could you please log an issue to fix this? Thanks!

2023-03-06 08:43 UTC, premun commented
Here: https://github.com/dotnet/arcade/issues/12792