Fix Solution Items
dotnet/arcade-services pull request #2654
Opened 2023-06-13 13:07 UTC by dkurepa

https://github.com/dotnet/arcade-services/issues/2329

2023-06-13 13:51 UTC, premun approved these changes

2023-06-19 11:51 UTC, premun requested changes
Do we want this? Doesn't this put the CodeCoverage in `eng/` in the VS too? Maybe we're fine having it top level there?

2023-06-19 11:53 UTC, dkurepa commented
It doesn't, they're all on the same level in the Solutions folder. Without this change, I'm getting an error when opening VS, and the solution folder is not loaded at all. I think @MilenaHristova was having the same issue

2023-06-19 11:54 UTC, premun approved these changes

2023-06-19 12:13 UTC, merged